# Edition and Feature Flags
style_edition = "2024"
unstable_features = true

# Brace and Parentheses Style
brace_style = "SameLineWhere"
remove_nested_parens = true

# Layout and Line Management
condense_wildcard_suffixes = true
error_on_line_overflow = true
fn_params_layout = "Tall"
overflow_delimited_expr = false
type_punctuation_density = "Wide"
where_single_line = false

# Comment and Documentation Formatting
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_code_in_doc_comments = true

# Attribute and Shorthand Usage
inline_attribute_width = 0
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Default"

# Match and Block Formatting
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false

# Code Structure and Reordering
reorder_impl_items = true
reorder_modules = true

# String and Macro Formatting
format_macro_matchers = true
format_strings = true

# Indentation Style
indent_style = "Block"

# Imports Configuration
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
reorder_imports = true

# Module and Struct Configuration
struct_field_align_threshold = 50

# Ignored Files
ignore = [
    "src/helper/const_str.rs",
    "src/helper/crypt/constants.rs",
]