brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
fn_params_layout = "Tall"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
inline_attribute_width = 50
match_arm_blocks = false
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
style_edition = "2024"
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = false
wrap_comments = true
error_on_line_overflow = true