macro_rules! declare_const_strings {
    ($($name:ident => $value:expr),*) => {
        $(
            pub(crate) const $name: &str = $value;
        )*
    };
}

declare_const_strings! {
    CERTIFICATE_NS       => "http://schemas.microsoft.com/office/2006/keyEncryptor/certificate",
    CHART_NS             => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart",
    CHART_TYPE           => "application/vnd.openxmlformats-officedocument.drawingml.chart+xml",
    COMMENTS_NS          => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments",
    COMMENTS_TYPE        => "application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml",
    THREADED_COMMENT_NS  => "http://schemas.microsoft.com/office/2017/10/relationships/threadedComment",
    THREADED_COMMENTS_NS => "http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments",
    PERSION_NS           => "http://schemas.microsoft.com/office/2017/10/relationships/person",
    PKG_PERSON           => "xl/persons/person.xml",
    CONTYPES_NS          => "http://schemas.openxmlformats.org/package/2006/content-types",
    CORE_PROPS_TYPE      => "application/vnd.openxmlformats-package.core-properties+xml",
    COREPROPS_NS         => "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
    COREPROPS_REL        => "http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties",
    CUSTOM_PROPS_NS      => "http://schemas.openxmlformats.org/officeDocument/2006/custom-properties",
    CUSTOM_PROPS_REL     => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties",
    CUSTOM_PROPS_TYPE    => "application/vnd.openxmlformats-officedocument.custom-properties+xml",
    CUSTOMUI_NS          => "http://schemas.microsoft.com/office/2006/relationships/ui/extensibility",
    DCMITYPE_NS          => "http://purl.org/dc/dcmitype/",
    DCORE_NS             => "http://purl.org/dc/elements/1.1/",
    DCTERMS_NS           => "http://purl.org/dc/terms/",
    DRAWING_CHART_NS     => "http://schemas.microsoft.com/office/drawing/2007/8/2/chart",
    DRAWING_CHART_2015_NS => "http://schemas.microsoft.com/office/drawing/2015/06/chart",
    DRAWING_MAIN_NS      => "http://schemas.microsoft.com/office/drawing/2010/main",
    DRAWING_TYPE         => "application/vnd.openxmlformats-officedocument.drawing+xml",
    DRAWINGML_CHART_NS   => "http://schemas.openxmlformats.org/drawingml/2006/chart",
    DRAWINGML_MAIN_NS    => "http://schemas.openxmlformats.org/drawingml/2006/main",
    DRAWINGS_NS          => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing",
    ENCRYPTION_NS        => "http://schemas.microsoft.com/office/2006/encryption",
    EXCEL_MAIN_NS        => "http://schemas.microsoft.com/office/excel/2006/main",
    EXCEL_NS             => "urn:schemas-microsoft-com:office:excel",
    HYPERLINK_NS         => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink",
    IMAGE_NS             => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/image",
    MC_NS                => "http://schemas.openxmlformats.org/markup-compatibility/2006",
    OFCDOC_NS            => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument",
    OFFICE_NS            => "urn:schemas-microsoft-com:office:office",
    OLE_OBJECT_NS        => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject",
    OLE_OBJECT_TYPE      => "application/vnd.openxmlformats-officedocument.oleObject",
    PACKAGE_NS           => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/package",
    PASSWORD_NS          => "http://schemas.microsoft.com/office/2006/keyEncryptor/password",
    PIVOT_CACHE_DEF_NS   => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotCacheDefinition",
    PRINTER_SETTINGS_NS  => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings",
    PRNTR_SETTINGS_TYPE  => "application/vnd.openxmlformats-officedocument.spreadsheetml.printerSettings",
    REL_NS               => "http://schemas.openxmlformats.org/package/2006/relationships",
    REL_OFC_NS           => "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    REL_TYPE             => "application/vnd.openxmlformats-package.relationships+xml",
    SHARED_STRINGS_NS    => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings",
    SHARED_STRINGS_TYPE  => "application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml",
    SHEET_DRAWING_NS     => "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing",
    SHEET_MAIN_NS        => "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
    SHEET_MS_MAIN_NS     => "http://schemas.microsoft.com/office/spreadsheetml/2009/9/main",
    SHEET_MS_REVISION_NS => "http://schemas.microsoft.com/office/spreadsheetml/2014/revision",
    SHEET_TYPE           => "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml",
    SHEETML_AC_NS        => "http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac",
    STYLES_NS            => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles",
    STYLES_TYPE          => "application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml",
    TABLE_NS             => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/table",
    PIVOT_TABLE_NS       => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotTable",
    TABLE_TYPE           => "application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml",
    PIVOT_TABLE_TYPE     => "application/vnd.openxmlformats-officedocument.spreadsheetml.pivotTable+xml",
    PIVOT_CACHE_DEF_TYPE => "application/vnd.openxmlformats-officedocument.spreadsheetml.pivotCacheDefinition+xml",
    THEME_NS             => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme",
    THEME_TYPE           => "application/vnd.openxmlformats-officedocument.theme+xml",
    VBA_PROJECT_NS       => "http://schemas.microsoft.com/office/2006/relationships/vbaProject",
    JSA_PROJECT_NS       => "http://schemas.onlyoffice.com/jsaProject",
    VBA_TYPE             => "application/vnd.ms-office.vbaProject",
    VML_DRAWING_NS       => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing",
    VML_DRAWING_TYPE     => "application/vnd.openxmlformats-officedocument.vmlDrawing",
    VML_NS               => "urn:schemas-microsoft-com:vml",
    VTYPES_NS            => "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes",
    WORKBOOK             => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    WORKBOOK_MACRO_TYPE  => "application/vnd.ms-excel.sheet.macroEnabled.main+xml",
    WORKBOOK_TYPE        => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml",
    WORKSHEET_NS         => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet",
    XPROPS_NS            => "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties",
    XPROPS_REL           => "http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties",
    XPROPS_TYPE          => "application/vnd.openxmlformats-officedocument.extended-properties+xml",
    XSI_NS               => "http://www.w3.org/2001/XMLSchema-instance",
    PKG_CHARTS           => "xl/charts",
    PKG_DRAWINGS         => "xl/drawings",
    PKG_DRAWINGS_RELS    => "xl/drawings/_rels/drawing",
    PKG_EMBEDDINGS       => "xl/embeddings",
    PKG_MEDIA            => "xl/media",
    PKG_PRNTR_SETTINGS   => "xl/printerSettings",
    PKG_SHARED_STRINGS   => "xl/sharedStrings.xml",
    PKG_SHEET            => "xl/worksheets/sheet",
    PKG_SHEET_RELS       => "xl/worksheets/_rels/sheet",
    PKG_STYLES           => "xl/styles.xml",
    PKG_TABLES           => "xl/tables",
    PKG_THEME            => "xl/theme/theme1.xml",
    PKG_VBA_PROJECT      => "xl/vbaProject.bin",
    PKG_JSA_PROJECT      => "xl/jsaProject.bin",
    PKG_VML_DRAWING_RELS => "xl/drawings/_rels/vmlDrawing",
    PKG_WORKBOOK         => "xl/workbook.xml",
    PKG_WORKBOOK_RELS    => "xl/_rels/workbook.xml.rels",

    ARC_APP              => "docProps/app.xml",
    ARC_CORE             => "docProps/core.xml",
    ARC_CUSTOM           => "docProps/custom.xml",
    CONTENT_TYPES        => "[Content_Types].xml"
}

// Ths file is ignored by rustfmt.
