/// A macro to simplify module usage and visibility.
///
/// This macro takes a list of modules, makes them private,
/// and re-exports their contents as public in the current scope.
macro_rules! pub_mod_use {
    ($($vis:vis $mod:ident),*) => {
        $(
            mod $mod;
            $vis use self::$mod::*;
        )*
    };
}

pub mod custom_properties;
pub mod drawing;
pub mod office;
pub mod office2010;
pub mod office2019;
pub mod raw;
pub mod vml;

pub_mod_use![
    pub(crate) borders_crate,
    pub(crate) borders,
    pub(crate) cell_format,
    pub(crate) cell_formats,
    pub(crate) cell_style_formats,
    pub(crate) cell_styles,
    pub(crate) colors,
    pub(crate) columns,
    pub(crate) differential_format,
    pub(crate) differential_formats,
    pub(crate) fills,
    pub(crate) fonts,
    pub(crate) media_object,
    pub(crate) merge_cells,
    pub(crate) mru_colors,
    pub(crate) numbering_formats,
    pub(crate) phonetic_run,
    pub(crate) rows,
    pub(crate) shared_string_item,
    pub(crate) shared_string_table,
    pub(crate) stylesheet,
    pub(crate) text,

    pub address,
    pub attributes,
    pub alignment,
    pub anchor,
    pub auto_filter,
    pub bold,
    pub boolean_value,
    pub border_properties_type,
    pub border_style_values,
    pub border,
    pub byte_value,
    pub cache_field,
    pub cache_fields,
    pub cache_source,
    pub cell_formula_values,
    pub cell_formula,
    pub cell_raw_value,
    pub cell_style,
    pub cell_value,
    pub cell,
    pub cells,
    pub chart_type,
    pub chart,
    pub color_scale,
    pub color,
    pub column_breaks,
    pub column_fields,
    pub column_items,
    pub column_reference,
    pub column,
    pub comment,
    pub comment_text,
    pub conditional_format_value_object_values,
    pub conditional_format_value_object,
    pub conditional_format_values,
    pub conditional_formatting_operator_values,
    pub conditional_formatting_rule,
    pub conditional_formatting,
    pub coordinate,
    pub csv_encode_values,
    pub csv_writer_option,
    pub data_bar,
    pub data_field,
    pub data_fields,
    pub date_time_value,
    pub data_validation_operator_values,
    pub data_validation_values,
    pub data_validation,
    pub data_validations,
    pub defined_name,
    pub double_value,
    pub embedded_object_properties,
    pub enum_trait,
    pub enum_value,
    pub error,
    pub field,
    pub fill,
    pub font_char_set,
    pub font_family_numbering,
    pub font_name,
    pub font_scheme_values,
    pub font_scheme,
    pub font_size,
    pub font,
    pub formula,
    pub from_marker,
    pub gradient_fill,
    pub gradient_stop,
    pub header_footer,
    pub horizontal_alignment_values,
    pub hyperlink,
    pub icon_set,
    pub image,
    pub int16_value,
    pub int32_value,
    pub int64_value,
    pub italic,
    pub item_values,
    pub location,
    pub member_property_index,
    pub numbering_format,
    pub object_anchor,
    pub odd_footer,
    pub odd_header,
    pub ole_object,
    pub ole_objects,
    pub orientation_values,
    pub page_margins,
    pub page_setup,
    pub pane_state_values,
    pub pane_values,
    pub pane,
    pub pattern_fill,
    pub pattern_values,
    pub pivot_cache_definition,
    pub pivot_field,
    pub pivot_fields,
    pub pivot_table_definition,
    pub pivot_table_style,
    pub pivot_table,
    pub print_options,
    pub properties,
    pub protection,
    pub r#break,
    pub range,
    pub rich_text,
    pub row_breaks,
    pub row_item,
    pub row_items,
    pub row_reference,
    pub row,
    pub s_byte_value,
    pub selection,
    pub sequence_of_references,
    pub shared_items,
    pub sheet_format_properties,
    pub sheet_protection,
    pub sheet_state_values,
    pub sheet_view_values,
    pub sheet_view,
    pub sheet_views,
    pub source_values,
    pub strike,
    pub string_value,
    pub style,
    pub table,
    pub text_element,
    pub time_period_values,
    pub to_marker,
    pub totals_row_function_values,
    pub true_false_blank_value,
    pub true_false_value,
    pub u_int16_value,
    pub u_int32_value,
    pub underline_values,
    pub underline,
    pub vertical_alignment_run_values,
    pub vertical_alignment_values,
    pub vertical_text_alignment,
    pub workbook_protection,
    pub workbook_view,
    pub workbook,
    pub worksheet_source,
    pub worksheet,
    pub writer_manager
];
