name: umya-spreadsheet

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: rustup component add rustfmt clippy

    - name: Run Lint & Tests
      run: |
        cargo clippy -- -D warnings
        cargo fmt --all -- --check
        cargo test
